package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/yaroslav-koval/graphql-psychologists-courses/graph/model"
)

// CreatePsychologist is the resolver for the createPsychologist field.
func (r *mutationResolver) CreatePsychologist(ctx context.Context, input model.NewPsychologist) (*model.Psychologist, error) {
	panic(fmt.Errorf("not implemented: CreatePsychologist - createPsychologist"))
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.NewCourse) (*model.Course, error) {
	panic(fmt.Errorf("not implemented: CreateCourse - createCourse"))
}

// CreateLesson is the resolver for the createLesson field.
func (r *mutationResolver) CreateLesson(ctx context.Context, input model.NewLesson) (*model.Lesson, error) {
	panic(fmt.Errorf("not implemented: CreateLesson - createLesson"))
}

// Psychologist is the resolver for the psychologist field.
func (r *queryResolver) Psychologist(ctx context.Context, id string) (*model.Psychologist, error) {
	return r.em.GetPsychologistByID(ctx, id)
}

// Psychologists is the resolver for the psychologists field.
func (r *queryResolver) Psychologists(ctx context.Context) ([]*model.Psychologist, error) {
	return r.em.GetAllPsychologists(ctx)
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, id string) (*model.Course, error) {
	return r.em.GetCourseByID(ctx, id)
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	return r.em.GetAllCourses(ctx)
}

// Lesson is the resolver for the lesson field.
func (r *queryResolver) Lesson(ctx context.Context, id string) (*model.Lesson, error) {
	return r.em.GetLessonByID(ctx, id)
}

// Lessons is the resolver for the lessons field.
func (r *queryResolver) Lessons(ctx context.Context) ([]*model.Lesson, error) {
	return r.em.GetAllLessons(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
