// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Description   *string         `json:"description,omitempty"`
	Price         int             `json:"price"`
	Psychologists []*Psychologist `json:"psychologists"`
	Lessons       []*Lesson       `json:"lessons"`
}

type Lesson struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Number int     `json:"number"`
	Course *Course `json:"course"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewCourse struct {
	Name          string   `json:"name"`
	Description   *string  `json:"description,omitempty"`
	Price         int      `json:"price"`
	Psychologists []string `json:"psychologists"`
}

type NewLesson struct {
	Name   string `json:"name"`
	Number int    `json:"number"`
	Course string `json:"course"`
}

type NewPsychologist struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Psychologist struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Courses     []*Course `json:"Courses,omitempty"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}
