// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewCourse struct {
	Name          string   `json:"name"`
	Description   *string  `json:"description,omitempty"`
	Price         int      `json:"price"`
	Psychologists []string `json:"psychologists"`
}

type NewLesson struct {
	Name   string `json:"name"`
	Number int    `json:"number"`
	Course string `json:"course"`
}

type NewPsychologist struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Query struct {
}

type UpdateCourse struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       int     `json:"price"`
}

type UpdateLesson struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Number int    `json:"number"`
}

type UpdatePsychologist struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}
